version: "3.8"
services:
  landmarks:
    build: .\
    ports:
      - "7000:8080"
      - "5005:5005"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USERNAME=postgres
      - POSTGRES_URL=jdbc:postgresql://landmarks-db:5432/landmarks
      - JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    depends_on:
      - landmarks-db
  landmarks-db:
    image: postgres
    expose:
      - 5432
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=landmarks
    restart: always
    volumes:
      - landmarks:/var/lib/postgresql/data
volumes:
  landmarks: