services:
  landmarks:
    build: .\
    ports:
      - "7000:8080"
      - "5005:5005"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://landmarks-db:5432/landmarks
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      #      - SPRING_LIQUIBASE_CHANGELOG=classpath:/db/changelog/db.changelog-master.yaml
      #      - JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    depends_on:
        - landmarks-db
  landmarks-db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=landmarks
    restart: always
    volumes:
      - landmarks:/var/lib/postgresql/data
volumes:
  landmarks: